#!/usr/bin/env bash
set -euo pipefail

# Shared helper: mandatory hardware selection profile for build/start scripts.
# File format: shell env file generated by scripts/hw_select.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
HW_SELECTION_FILE_DEFAULT="$ROOT_DIR/.hw_selection.env"

_hw_fail() {
  echo "ERR: $*" >&2
  exit 2
}

_hw_require_int_range() {
  local name="$1"
  local val="$2"
  local lo="$3"
  local hi="$4"
  [[ "$val" =~ ^[0-9]+$ ]] || _hw_fail "$name must be an integer (got '$val')"
  if (( val < lo || val > hi )); then
    _hw_fail "$name must be in range [$lo..$hi] (got '$val')"
  fi
}

load_hw_selection_or_die() {
  local file="${HW_SELECTION_FILE:-$HW_SELECTION_FILE_DEFAULT}"
  [[ -f "$file" ]] || _hw_fail "missing hardware selection file: $file (run: bash scripts/hw_select.sh ...)"

  # shellcheck source=/dev/null
  source "$file"

  [[ "${HW_POOL_VERSION:-}" == "1" ]] || _hw_fail "invalid HW_POOL_VERSION in $file"
  [[ "${HW_CPU_PLATFORM:-}" == "xeon_e5-2680_v4_256gb_ddr4" ]] || _hw_fail "unsupported HW_CPU_PLATFORM in $file"

  _hw_require_int_range "HW_GPU_2080TI_11GB_COUNT" "${HW_GPU_2080TI_11GB_COUNT:-}" 1 2
  _hw_require_int_range "HW_GPU_2080TI_22GB_COUNT" "${HW_GPU_2080TI_22GB_COUNT:-}" 1 2
  _hw_require_int_range "HW_GPU_3080TI_10GB_COUNT" "${HW_GPU_3080TI_10GB_COUNT:-}" 0 1
  if [[ -z "${HW_REQUIRE_NVLINK_11GB_PAIR:-}" ]]; then
    if (( HW_GPU_2080TI_11GB_COUNT >= 2 )); then
      HW_REQUIRE_NVLINK_11GB_PAIR=1
    else
      HW_REQUIRE_NVLINK_11GB_PAIR=0
    fi
  fi
  _hw_require_int_range "HW_REQUIRE_NVLINK_11GB_PAIR" "${HW_REQUIRE_NVLINK_11GB_PAIR:-}" 0 1
  case "${HW_MODEL_QUANT:-q8}" in
    q8) ;;
    *)
      _hw_fail "unsupported HW_MODEL_QUANT='${HW_MODEL_QUANT:-}' in selection file (only q8 is enabled in production mainline)"
      ;;
  esac

  HW_GPU_TOTAL=$((HW_GPU_2080TI_11GB_COUNT + HW_GPU_2080TI_22GB_COUNT + HW_GPU_3080TI_10GB_COUNT))
}

# Derives canonical runtime flags from the selected hardware pool.
# Exports:
#   HW_GPU_TOTAL
#   HW_DERIVED_TOPOLOGY_MODE (max_model_fast|single_lane)
#   HW_DERIVED_ENABLE_SOLO_3080 (0|1)
#   HW_DERIVED_REQUIRE_NVLINK (0|1)
#   HW_DERIVED_HW_BASE_PROFILE (auto|A|B|D)
#   HW_DERIVED_CUDA_ARCH_LIST (75|75,86)
#   HW_DERIVED_MODEL_QUANT (q8 only)
derive_hw_runtime_flags() {
  : "${HW_GPU_2080TI_11GB_COUNT:?call load_hw_selection_or_die first}"
  : "${HW_GPU_2080TI_22GB_COUNT:?call load_hw_selection_or_die first}"
  : "${HW_GPU_3080TI_10GB_COUNT:?call load_hw_selection_or_die first}"

  HW_DERIVED_MODEL_QUANT="${HW_MODEL_QUANT:-q8}"

  if (( HW_GPU_3080TI_10GB_COUNT >= 1 )); then
    HW_DERIVED_CUDA_ARCH_LIST="75,86"
  else
    HW_DERIVED_CUDA_ARCH_LIST="75"
  fi

  # Full hetero profile exists only when we can form the classic 22 + 11 + 11 lane.
  if (( HW_GPU_2080TI_22GB_COUNT >= 1 && HW_GPU_2080TI_11GB_COUNT >= 2 )); then
    HW_DERIVED_TOPOLOGY_MODE="max_model_fast"
    HW_DERIVED_ENABLE_SOLO_3080="$HW_GPU_3080TI_10GB_COUNT"

    if (( HW_GPU_2080TI_22GB_COUNT == 1 && HW_GPU_2080TI_11GB_COUNT == 2 && HW_GPU_3080TI_10GB_COUNT == 0 )); then
      HW_DERIVED_HW_BASE_PROFILE="A"
    elif (( HW_GPU_2080TI_22GB_COUNT == 1 && HW_GPU_2080TI_11GB_COUNT == 2 && HW_GPU_3080TI_10GB_COUNT == 1 )); then
      HW_DERIVED_HW_BASE_PROFILE="B"
    elif (( HW_GPU_2080TI_22GB_COUNT == 2 && HW_GPU_2080TI_11GB_COUNT == 2 && HW_GPU_3080TI_10GB_COUNT == 0 )); then
      HW_DERIVED_HW_BASE_PROFILE="D"
    else
      HW_DERIVED_HW_BASE_PROFILE="auto"
    fi
  else
    # Reduced pools are routed through a safe single-lane topology (world=1 on 22GB lane).
    HW_DERIVED_TOPOLOGY_MODE="single_lane"
    HW_DERIVED_ENABLE_SOLO_3080="0"
    HW_DERIVED_HW_BASE_PROFILE="auto"
  fi
  HW_DERIVED_REQUIRE_NVLINK="$HW_REQUIRE_NVLINK_11GB_PAIR"

  export HW_GPU_TOTAL
  export HW_DERIVED_TOPOLOGY_MODE
  export HW_DERIVED_ENABLE_SOLO_3080
  export HW_DERIVED_REQUIRE_NVLINK
  export HW_DERIVED_HW_BASE_PROFILE
  export HW_DERIVED_CUDA_ARCH_LIST
  export HW_DERIVED_MODEL_QUANT
}

print_hw_selection_summary() {
  echo "[hw-select] cpu=$HW_CPU_PLATFORM gpu_pool=(11gb:${HW_GPU_2080TI_11GB_COUNT},22gb:${HW_GPU_2080TI_22GB_COUNT},3080_10gb:${HW_GPU_3080TI_10GB_COUNT}) total=$HW_GPU_TOTAL require_nvlink_11gb_pair=$HW_REQUIRE_NVLINK_11GB_PAIR"
  echo "[hw-select] derived topology=$HW_DERIVED_TOPOLOGY_MODE enable_solo_3080=$HW_DERIVED_ENABLE_SOLO_3080 require_nvlink=$HW_DERIVED_REQUIRE_NVLINK hw_base_profile=$HW_DERIVED_HW_BASE_PROFILE cuda_arch_list=$HW_DERIVED_CUDA_ARCH_LIST quant=$HW_DERIVED_MODEL_QUANT"
}
