#!/usr/bin/env bash
set -euo pipefail

# Mandatory hardware pool selection for this repository.
# Writes .hw_selection.env used by build/start scripts.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="${HW_SELECTION_FILE:-$ROOT_DIR/.hw_selection.env}"

# Default pool: 1x 22GB + 2x 11GB (NVLink expected on 11GB pair), no 3080.
gpu11="2"
gpu22="1"
gpu3080="0"
require_nvlink_11gb_pair="1"
model_quant="q8"

usage() {
  cat <<EOF
Usage:
  $0 [--gpu-2080ti-11gb <1|2>] [--gpu-2080ti-22gb <1|2>] [--gpu-3080ti-10gb <0|1>] [--require-nvlink-11gb-pair <0|1>] [--model-quant q8]

Example:
  $0
  # writes defaults: 11gb=2, 22gb=1, 3080_10gb=0, require_nvlink_11gb_pair=1, quant=q8
EOF
}

require_int_range() {
  local name="$1" val="$2" lo="$3" hi="$4"
  [[ "$val" =~ ^[0-9]+$ ]] || { echo "ERR: $name must be integer" >&2; exit 2; }
  if (( val < lo || val > hi )); then
    echo "ERR: $name must be in [$lo..$hi] (got $val)" >&2
    exit 2
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --gpu-2080ti-11gb) gpu11="${2:-}"; shift 2 ;;
    --gpu-2080ti-22gb) gpu22="${2:-}"; shift 2 ;;
    --gpu-3080ti-10gb) gpu3080="${2:-}"; shift 2 ;;
    --require-nvlink-11gb-pair) require_nvlink_11gb_pair="${2:-}"; shift 2 ;;
    --model-quant) model_quant="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "ERR: unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

require_int_range "--gpu-2080ti-11gb" "$gpu11" 1 2
require_int_range "--gpu-2080ti-22gb" "$gpu22" 1 2
require_int_range "--gpu-3080ti-10gb" "$gpu3080" 0 1
require_int_range "--require-nvlink-11gb-pair" "$require_nvlink_11gb_pair" 0 1
case "$model_quant" in
  q8) ;;
  *) echo "ERR: --model-quant must be q8 (native q4 is not enabled in production mainline)" >&2; exit 2 ;;
esac

total=$((gpu11 + gpu22 + gpu3080))
ts="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$OUT_FILE" <<EOF
# Auto-generated by scripts/hw_select.sh
HW_POOL_VERSION=1
HW_SELECTED_AT_UTC="$ts"
HW_CPU_PLATFORM="xeon_e5-2680_v4_256gb_ddr4"
HW_GPU_2080TI_11GB_COUNT=$gpu11
HW_GPU_2080TI_22GB_COUNT=$gpu22
HW_GPU_3080TI_10GB_COUNT=$gpu3080
HW_REQUIRE_NVLINK_11GB_PAIR=$require_nvlink_11gb_pair
HW_GPU_TOTAL=$total
HW_MODEL_QUANT="$model_quant"
EOF

echo "[ok] wrote hardware selection: $OUT_FILE"
echo "[ok] pool -> 2080ti_11gb=$gpu11 2080ti_22gb=$gpu22 3080ti_10gb=$gpu3080 total=$total require_nvlink_11gb_pair=$require_nvlink_11gb_pair quant=$model_quant"
echo "Next step: run start/build scripts normally; they now enforce this selection."
